
name: Update refdoc
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-refdoc.yaml
      - refdoc.yaml
env:
  branch_name: update-refdoc
  email: github-actions[bot]@users.noreply.github.com
  username: github-actions[bot]
jobs:
  update:
    name: Update Refdoc
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Update
        uses: streamwest-1629/refdoc@0.1.3
        with:
          refdoc: refdoc.yaml
      - name: Set current datetime as env variable and git push
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: ${{ env.email }}
          author_name: ${{ env.username }}
          message: Update Refdoc at ${{ env.CURRENT_DATETIME }}
          branch: ${{ github.ref_name }}
